// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: queries.sql

package db

import (
	"context"
)

const getUser = `-- name: GetUser :one
SELECT id, uuid, email, first_name, last_name, auth_provider_id, auth_provider, created_at, updated_at, auth_provider_opt_code, last_synced_at, last_synced_by
FROM users
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.AuthProviderID,
		&i.AuthProvider,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AuthProviderOptCode,
		&i.LastSyncedAt,
		&i.LastSyncedBy,
	)
	return i, err
}
